version: 0.2

phases:
  install:
    commands:
      - TAG_NAME=latest
      - echo $AWS_DEFAULT_REGION
      - echo $REPOSITORY_URI
      - echo $TAG_NAME
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
     - $(aws ecr get-login --region $AWS_REGION --no-include-email)
     
  build:
    commands:
      - echo Building the Docker image... 
      - envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./.env.example > ./.env
      - echo "$(cat ./.env)"
      - docker build -t ai-genarative-be-repo .
      - docker tag ai-genarative-be-repo:latest 989299900151.dkr.ecr.ap-south-1.amazonaws.com/ai-genarative-be-repo:latest
      

  post_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 989299900151.dkr.ecr.ap-south-1.amazonaws.com/ai-genarative-be-repo:latest
      - bash ./deploy.sh